// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://badijucpmieqwoqlvjia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZGlqdWNwbWllcXdvcWx2amlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTc3MzksImV4cCI6MjA3MTg5MzczOX0.r6dsJ5wRylQI-U49oa_uebDt1yopgdVvk3S4UaIOnis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});